# Docker Compose configuration for the Dev Container

services:
  main:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspace
